environment:
  RUSTUP_USE_HYPER: 1
install:
  # Download and instal rustup, the CLI tool form https://rustup.rs
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

build: false

test_script:
  - cargo build
